float Temp;int pinA=13, pinB=12, pinC=11, pinD=10, pinE=9, pinF=8, pinG=7, pinP=6;
int left=5,right=4;
#define echoPin 2 // attach pin D2 Arduino to pin Echo of HC-SR04
#define trigPin 3 //attach pin D3 Arduino to pin Trig of HC-SR04
long duration; // variable for the duration of sound wave travel
int distance; // variable for the distance measurement
int pushButton=A1;
int type=0;
void setup(){
  Serial.begin(9600);
  pinMode(A0,INPUT);pinMode(pinA, OUTPUT); pinMode(pinB, OUTPUT); pinMode(A1,INPUT);
  pinMode(pinC, OUTPUT);pinMode(pinD, OUTPUT); pinMode(pinE, OUTPUT);
  pinMode(pinF, OUTPUT);pinMode(pinG, OUTPUT); pinMode(pinP, OUTPUT);
  pinMode(left, OUTPUT); pinMode(right, OUTPUT);pinMode(pushButton, INPUT);
  pinMode(trigPin, OUTPUT); // Sets the trigPin as an OUTPUT
  pinMode(echoPin, INPUT); // Sets the echoPin as an INPUT
}
void showSevenSeg(byte A, byte B, byte C, byte D, byte E, byte F, byte G, byte P) {
digitalWrite(pinA, A); digitalWrite(pinB, B); digitalWrite(pinC, C);
digitalWrite(pinD, D); digitalWrite(pinE, E); digitalWrite(pinF, F);
digitalWrite(pinG, G); digitalWrite(pinP, P);
}
void loop(){
  int mode=0;
  int t3,t2,t1;
  int d3,d2,d1;
  int buttonState=digitalRead(pushButton);
  if(buttonState==HIGH && type==0) type=1;
  else if(buttonState==HIGH && type==1) type=0;
  Temp = analogRead(A0);
  Temp = (Temp / 1024*5)/0.01;  
  int temp=Temp/1;
  t3=temp/10;
  t2=temp%10;
  t1=(Temp-temp)*10;
  if(type==1){
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  // Sets the trigPin HIGH (ACTIVE) for 10 microseconds
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigPin, LOW);
  // Reads the echoPin, returns the sound wave travel time in microseconds
  duration = pulseIn(echoPin, HIGH);
  // Calculating the distance
  distance = duration * 0.034 / 2; // Speed of sound wave divided by 2 (go and back)
  // Displays the distance on the Serial Monitor
  int distan=distance/1;
  d3=distan/100;
  d2=(distan%100)/10;
  d1=distance%10;
  if(mode==0) mode=1;
  else mode=0;
  }
  if(mode==0){
    switch(t3){
      case 0: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,0,0,1,1);
              delay(500);
              break;
      case 1: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,0,0,1,1,1,1,1);
              delay(500);
              break;
      case 2: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,1,0,0,1,0,1);
              delay(500);
              break;
      case 3: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,1,1,0,1);
              delay(500);
              break;
      case 4: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,0,0,1,1,0,0,1);
              delay(500);
              break;
      case 5: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,0,0,1,0,0,1);
              delay(500);
              break;
      case 6: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,0,0,0,0,0,1);
              delay(500);
              break;
      case 7: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,1,1,1,1,1);
              delay(500);
              break;
      case 8: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,0,0,0,1);
              delay(500);
              break;
      case 9: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,1,1,0,0,1);
              delay(500);
              break;
    }
    for(int i=0; i<100; i++){
      switch(t3){
      case 0: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,0,0,1,1);
              delay(5);
              break;
      case 1: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 2: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,1,0,0,1,0,1);
              delay(5);
              break;
      case 3: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,1,1,0,1);
              delay(5);
              break;
      case 4: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,0,0,1,1,0,0,1);
              delay(5);
              break;
      case 5: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,0,0,1,0,0,1);
              delay(5);
              break;
      case 6: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,0,0,0,0,0,1);
              delay(5);
              break;
      case 7: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 8: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,0,0,0,1);
              delay(5);
              break;
      case 9: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,1,1,0,0,1);
              delay(5);
              break;
    }
     switch(t2){
       case 0: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,0,0,1,1);
              delay(5);
              break;
      case 1: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 2: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,1,0,0,1,0,1);
              delay(5);
              break;
      case 3: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,1,1,0,1);
              delay(5);
              break;
      case 4: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,0,0,1,1,0,0,1);
              delay(5);
              break;
      case 5: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,0,0,1,0,0,1);
              delay(5);
              break;
      case 6: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,0,0,0,0,0,1);
              delay(5);
              break;
      case 7: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 8: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,0,0,0,1);
              delay(5);
              break;
      case 9: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,1,1,0,0,1);
              delay(5);
              break;
     }
    }
      for(int i=0; i<100; i++){
      switch(t2){
      case 0: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,0,0,1,1);
              delay(5);
              break;
      case 1: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 2: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,1,0,0,1,0,1);
              delay(5);
              break;
      case 3: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,1,1,0,1);
              delay(5);
              break;
      case 4: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,0,0,1,1,0,0,1);
              delay(5);
              break;
      case 5: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,0,0,1,0,0,1);
              delay(5);
              break;
      case 6: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,0,0,0,0,0,1);
              delay(5);
              break;
      case 7: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 8: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,0,0,0,1);
              delay(5);
              break;
      case 9: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,1,1,0,0,1);
              delay(5);
              break;
    }
              digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,1,1,1,1,1,1,0);
              delay(5);
    }
      for(int i=0; i<100; i++){
              digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,1,1,1,1,1,1,0);
              delay(5);
     switch(t1){
       case 0: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,0,0,1,1);
              delay(5);
              break;
      case 1: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 2: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,1,0,0,1,0,1);
              delay(5);
              break;
      case 3: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,1,1,0,1);
              delay(5);
              break;
      case 4: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,0,0,1,1,0,0,1);
              delay(5);
              break;
      case 5: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,0,0,1,0,0,1);
              delay(5);
              break;
      case 6: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,0,0,0,0,0,1);
              delay(5);
              break;
      case 7: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 8: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,0,0,0,1);
              delay(5);
              break;
      case 9: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,1,1,0,0,1);
              delay(5);
              break;
     }
    }
     for(int i=0; i<100; i++){
     switch(t1){
       case 0: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,0,0,1,1);
              delay(5);
              break;
      case 1: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 2: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,1,0,0,1,0,1);
              delay(5);
              break;
      case 3: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,1,1,0,1);
              delay(5);
              break;
      case 4: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,0,0,1,1,0,0,1);
              delay(5);
              break;
      case 5: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,0,0,1,0,0,1);
              delay(5);
              break;
      case 6: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,0,0,0,0,0,1);
              delay(5);
              break;
      case 7: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 8: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,0,0,0,1);
              delay(5);
              break;
      case 9: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,1,1,0,0,1);
              delay(5);
              break;
     }
              digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,1,1,1,0,0,1);
              delay(5);
    }
    for(int i=0; i<100; i++){
              digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,1,1,1,0,0,1);
              delay(5);
              digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,1,0,0,0,1,1);
              delay(5);
    }
              digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,1,0,0,0,1,1);
              delay(500);
  }
  if(mode==1){
    switch(d3){
      case 0: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,0,0,1,1);
              delay(500);
              break;
      case 1: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,0,0,1,1,1,1,1);
              delay(500);
              break;
      case 2: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,1,0,0,1,0,1);
              delay(500);
              break;
      case 3: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,1,0,1,1,0,1);
              delay(500);
              break;
      case 4: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,0,0,1,1,0,0,1);
              delay(500);
              break;
      case 5: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,0,0,1,0,0,1);
              delay(500);
              break;
      case 6: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,0,0,0,0,0,1);
              delay(500);
              break;
      case 7: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,1,1,1,1,1);
              delay(500);
              break;
      case 8: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,0,0,0,1);
              delay(500);
              break;
      case 9: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,1,1,0,0,1);
              delay(500);
              break;
    }
    for(int i=0; i<100; i++){
      switch(d3){
      case 0: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,0,0,1,1);
              delay(5);
              break;
      case 1: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 2: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,1,0,0,1,0,1);
              delay(5);
              break;
      case 3: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,1,1,0,1);
              delay(5);
              break;
      case 4: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,0,0,1,1,0,0,1);
              delay(5);
              break;
      case 5: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,0,0,1,0,0,1);
              delay(5);
              break;
      case 6: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,0,0,0,0,0,1);
              delay(5);
              break;
      case 7: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 8: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,0,0,0,1);
              delay(5);
              break;
      case 9: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,1,1,0,0,1);
              delay(5);
              break;
    }
     switch(d2){
       case 0: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,0,0,1,1);
              delay(5);
              break;
      case 1: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 2: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,1,0,0,1,0,1);
              delay(5);
              break;
      case 3: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,1,1,0,1);
              delay(5);
              break;
      case 4: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,0,0,1,1,0,0,1);
              delay(5);
              break;
      case 5: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,0,0,1,0,0,1);
              delay(5);
              break;
      case 6: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,0,0,0,0,0,1);
              delay(5);
              break;
      case 7: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 8: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,0,0,0,1);
              delay(5);
              break;
      case 9: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,1,1,0,0,1);
              delay(5);
              break;
     }
    }
      for(int i=0; i<100; i++){
      switch(d2){
      case 0: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,0,0,1,1);
              delay(5);
              break;
      case 1: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 2: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,1,0,0,1,0,1);
              delay(5);
              break;
      case 3: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,1,1,0,1);
              delay(5);
              break;
      case 4: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,0,0,1,1,0,0,1);
              delay(5);
              break;
      case 5: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,0,0,1,0,0,1);
              delay(5);
              break;
      case 6: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,0,0,0,0,0,1);
              delay(5);
              break;
      case 7: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 8: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,0,0,0,1);
              delay(5);
              break;
      case 9: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,1,1,0,0,1);
              delay(5);
              break;
    }
       switch(d1){
       case 0: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,0,0,1,1);
              delay(5);
              break;
      case 1: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 2: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,1,0,0,1,0,1);
              delay(5);
              break;
      case 3: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,1,1,0,1);
              delay(5);
              break;
      case 4: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,0,0,1,1,0,0,1);
              delay(5);
              break;
      case 5: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,0,0,1,0,0,1);
              delay(5);
              break;
      case 6: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,0,0,0,0,0,1);
              delay(5);
              break;
      case 7: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 8: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,0,0,0,0,1);
              delay(5);
              break;
      case 9: digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,0,0,1,1,0,0,1);
              delay(5);
              break;
     }
    }
      for(int i=0; i<100; i++){
      switch(d1){
      case 0: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,0,0,1,1);
              delay(5);
              break;
      case 1: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 2: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,1,0,0,1,0,1);
              delay(5);
              break;
      case 3: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,1,1,0,1);
              delay(5);
              break;
      case 4: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,0,0,1,1,0,0,1);
              delay(5);
              break;
      case 5: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,0,0,1,0,0,1);
              delay(5);
              break;
      case 6: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,0,0,0,0,0,1);
              delay(5);
              break;
      case 7: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,1,1,1,1,1);
              delay(5);
              break;
      case 8: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,0,0,0,0,1);
              delay(5);
              break;
      case 9: digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,0,0,1,1,0,0,1);
              delay(5);
              break;
    }
              digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(0,1,1,0,0,0,1,1);
              delay(5);
    }
     for(int i=0; i<100; i++){
              digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(0,1,1,0,0,0,1,1);
              delay(5);
              digitalWrite(4,LOW);
              digitalWrite(5,HIGH);
              showSevenSeg(1,1,0,1,0,1,0,1);
              delay(5);
    }
              digitalWrite(4,HIGH);
              digitalWrite(5,LOW);
              showSevenSeg(1,1,0,1,0,1,0,1);
              delay(500);
  }
}
